name: ${project.name}

main: com.easterlyn.EasterlynMachines
version: ${project.version}-${timestamp}
author: Jikoo
description: Multi-block machines!
api-version: "1.14"
depend: [Easterlyn-Core, Easterlyn-Captcha]
softdepend: [CreeperHeal]
