name: Easterlyn

main: com.easterlyn.Easterlyn
version: ${timestamp}
author: Jikoo
authors: [Dublek, FireNG, tmathmeyer]
description: https://www.youtube.com/watch?v=QHnJ9NmK3Pc
depend: [GriefPrevention, ProtocolLib]
softdepend: [CreeperHeal, dynmap, Regionerator, LuckPerms, WorldEdit, WorldGuard]
api-version: "1.14"

permissions:
 easterlyn.guildleader:
  description: 'Default false - not all horrorterrors are guild leaders.'
  default: false
