name: ${project.name}

main: com.easterlyn.captcha.EasterlynCaptcha
version: ${project.version}-${timestamp}
author: Jikoo
description: Captcha cards!
api-version: "1.14"
softdepend: [Easterlyn-Core]
