name: ${project.name}

main: com.easterlyn.${project.name}
version: ${project.version}-${timestamp}
author: Jikoo
description: ${project.description}
api-version: ${bukkit-api-version}
depend: [ EasterlynCore ]
# N.B. Reflections library requires Javassist library
libraries:
  - org.javassist:javassist:${javassist.version}
  - org.reflections:reflections:${reflections.version}
