name: ${project.name}

main: com.easterlyn.${project.name}
version: ${project.version}-${timestamp}
author: Jikoo
description: ${project.description}
depend: [LuckPerms]
softdepend: [GriefPrevention, WorldGuard]
