name: ${project.name}

main: com.easterlyn.EasterlynDiscord
version: ${project.version}-${timestamp}
author: Jikoo
description: Discord-Minecraft bridge plugin.
api-version: "1.14"
depend: [Easterlyn-Core, Easterlyn-Chat]
