name: ${project.name}

main: com.easterlyn.EasterlynEffects
version: ${project.version}-${timestamp}
author: Jikoo
description: Custom effects appearing like enchantments.
api-version: "1.14"
depend: [Easterlyn-Core]
