name: ${project.name}

main: com.easterlyn.${project.name}
version: ${project.version}-${timestamp}
author: Jikoo
description: ${project.description}
api-version: ${bukkit-api-version}
depend: [ EasterlynCore, EasterlynCaptchas ]
softdepend: [ WorldEdit ]
