name: Build Easterlyn

on:
  push:
  create:
    types: [tag]
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven repo
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Install NMS dependency
        if: steps.cache.outputs.cache-hit != 'true'
        # TODO extract version so it can be changed in a single place
        run: |
          mkdir ~/buildtools
          cd ~/buildtools
          wget -O buildtools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar buildtools.jar --remapped --rev 1.19

      - name: Build with Maven
        run: |
          mkdir ~/target
          mvn clean package --file pom.xml -Dproject.build.finaldir=~/target -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2

      - name: Publish artifacts
        if: github.event_name != 'pull_request_target' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            ~/target/*.jar
            !~/target/original-*.jar
