name: Build Easterlyn

on:
  push:
  create:
    types: [tag]
  pull_request_target:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven repo
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Install Paper dependency
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./paperclip
        # TODO extract version so it can be changed in a single place
        run: |
          wget -O paperclip.jar https://papermc.io/api/v1/paper/1.16.4/latest/download
          java -jar -Dpaperclip.install=true paperclip.jar

      - name: Build with Maven
        run: |
          mkdir ~/target
          mvn clean package --file pom.xml -X -Dproject.build.finaldir=~/target -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2

      - name: Publish artifacts
        if: github.event_name != 'pull_request_target'
        uses: marvinpinto/action-automatic-releases@v1.1.0
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: ${{ github.event.name != 'create' }}
          files: |
            ~/target/*.jar
            !~/target/original-*.jar
